### ISSUE TITLE
.config/lite-xl/plugins/lintplus/liteipc.lua:89: attempt to use a closed file at /usr/share/lite-xl/core/init.lua:1365

### ISSUE THREAD

**Issue by KikyTokamuro** [liquidev/lintplus#18] opened 2022-02-12 19:26 UTC
Error when initializing linterplus. Tell me, maybe I'm doing something wrong.

Version: Lite XL 2.0.5-luajit

init.lua:
```lua
local lintplus = require "plugins.lintplus"
lintplus.setup.lint_on_doc_load()
lintplus.setup.lint_on_doc_save()

config.plugins.lintplus = true
config.plugins.lintplus_php = true
```

Folder structure:
```
.config/lite-xl/plugins/
       lintplus/
       lintplus_php.lua
```

**Comment by liquidev** [comment] 2022-02-13 10:37
That's weird. I'm not sure what's happening there, the file shouldn't be closed prematurely like that.

**Comment by liquidev** [comment] 2022-02-18 07:18
I just merged a Pull Request that removes the old IPC library in favor of using Lite XL's provided `process` API. Please try pulling latest commits from `master` and see if it works now.

**Comment by KikyTokamuro** [comment] 2022-02-18 10:27
> I just merged a Pull Request that removes the old IPC library in favor of using Lite XL's provided `process` API. Please try pulling latest commits from `master` and see if it works now.

Now, when saving, it gives the following error:

`[Fri Feb 18 13:17:44 2022] lint+/php: index.php: linter exited with signal -110 : Connection timed out at .config/lite-xl/plugins/lintplus/init.lua:229`

**Comment by jgmdev** [comment] 2022-04-18 18:36
Can't reproduce, but make sure you are using latest changes from this repo and the `cli` version of PHP is the one been exported in your PATH
```
~ php -v
PHP 8.1.5 (cli) (built: Apr 14 2022 00:36:46) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies
```
Closing this since it should work now unless you have something not properly setup.

**Closed by jgmdev** 2022-04-18 18:36 UTC
